'use strict';
/*
 * Generates js/core/icons.js containing only the Lucide icons the app uses.
 * Run: node scripts/build-icons.js   (needs scripts/vendor/lucide.min.js, dev only)
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ICONS = {
  dashboard: 'LayoutDashboard', sell: 'ShoppingCart', sales: 'ReceiptText', customers: 'Users', products: 'Package',
  inventory: 'Warehouse', reports: 'BarChart3', expenses: 'Wallet', activity: 'History', settings: 'Settings',
  lock: 'Lock', unlock: 'Unlock', search: 'Search', barcode: 'ScanBarcode', x: 'X', plus: 'Plus', minus: 'Minus',
  trash: 'Trash2', edit: 'Pencil', eye: 'Eye', eyeOff: 'EyeOff', printer: 'Printer', file: 'FileText', download: 'Download',
  upload: 'Upload', left: 'ChevronLeft', right: 'ChevronRight', down: 'ChevronDown', up: 'ChevronUp', calendar: 'CalendarDays', check: 'Check',
  checkCircle: 'CheckCircle2', warning: 'AlertTriangle', alert: 'AlertCircle', info: 'Info', user: 'User', userPlus: 'UserPlus',
  bookmark: 'Bookmark', drafts: 'FolderOpen', returnIcon: 'Undo2', ban: 'Ban', cash: 'Banknote', card: 'CreditCard',
  trendUp: 'TrendingUp', trendDown: 'TrendingDown', boxes: 'Boxes', packagePlus: 'PackagePlus', packageMinus: 'PackageMinus',
  clipboard: 'ClipboardList', sliders: 'SlidersHorizontal', filter: 'ListFilter', refresh: 'RefreshCw', save: 'Save',
  drive: 'HardDrive', database: 'Database', shield: 'ShieldCheck', key: 'KeyRound', keyboard: 'Keyboard', tag: 'Tag',
  clock: 'Clock', archive: 'Archive', restore: 'ArchiveRestore', more: 'MoreHorizontal', external: 'ExternalLink', phone: 'Phone',
  pin: 'MapPin', percent: 'Percent', coins: 'Coins', handCoins: 'HandCoins', bag: 'ShoppingBag', store: 'Store',
  truck: 'Truck', layers: 'Layers', pie: 'PieChart', folder: 'Folder', copy: 'Copy', arrowRight: 'ArrowRight',
  arrowUp: 'ArrowUpRight', arrowDown: 'ArrowDownRight', hourglass: 'Hourglass', receipt: 'Receipt', box: 'Box', list: 'List', grid: 'LayoutGrid'
};

const ctx = {};
ctx.window = ctx; ctx.self = ctx; ctx.globalThis = ctx;
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname, 'vendor', 'lucide.min.js'), 'utf8'), ctx);
const lib = ctx.lucide.icons || ctx.lucide;

function nodeToSvg([tag, attrs, children]) {
  const a = Object.entries(attrs || {}).map(([k, v]) => `${k}="${v}"`).join(' ');
  const inner = (children || []).map(nodeToSvg).join('');
  return inner ? `<${tag} ${a}>${inner}</${tag}>` : `<${tag} ${a}/>`;
}

const out = {};
const missing = [];
for (const [key, name] of Object.entries(ICONS)) {
  const node = lib[name];
  if (!node) { missing.push(name); continue; }
  out[key] = (node[2] || []).map(nodeToSvg).join('');
}
if (missing.length) {
  console.error('Missing icons:', missing.join(', '));
  process.exit(1);
}
const file = `/* Generated by scripts/build-icons.js from Lucide (ISC licence). Do not edit by hand. */
'use strict';
window.ICON_PATHS = ${JSON.stringify(out)};
`;
fs.writeFileSync(path.join(__dirname, '..', 'js', 'core', 'icons.js'), file);
console.log(`Wrote ${Object.keys(out).length} icons (${file.length} bytes)`);
